$ANSIBLE_VAULT;1.1;AES256
63383261303834623664643436396530353866666566373865643862666262333833646664386535
6163343862366264613730366664343739613932393836320a333436306537313339633363396636
34663662316565303433336234306663636563383661376465366163343065663731336566343065
3262623239623061370a353066663635363637663665333438383237336438616535376562363365
39313663393564353035343931643466383762376466393334356335363561323562366662323364
34613463616564326638306230376264373137663431383635666230333536383862366135343431
39623736643030393036363636393365653630306535313362623430343839336663363362326336
36396334306364366330616531343565373637313365623331376439366539393764623663386665
65653564613231636532333234386330656239343939303362656261323836346361636664666466
36656236346363306461336266613966336434346261613534353033646363356139353839383331
363230373533313030356439643862393333
