grpc:
  server:
    port: 50057
  client:
    rider-service:
      address: 'static://${RIDER_SERVICE_HOST:localhost}:${RIDER_SERVICE_PORT:50054}'
      negotiationType: plaintext
    driver-service:
      address: 'static://${DRIVER_SERVICE_HOST:localhost}:${DRIVER_SERVICE_PORT:50053}'
      negotiationType: plaintext
    notification-service:
      address: 'static://${NOTIFICATION_SERVICE_HOST:localhost}:${NOTIFICATION_SERVICE_PORT:50058}'
      negotiationType: plaintext
    user-service:
      address: 'static://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:50052}'
      negotiationType: plaintext

spring:
  application:
    name: trip-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: lastmile_trips
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    root: INFO
    com.lastmile: DEBUG

