apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lastmile-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - lastmile.local
    secretName: lastmile-tls
  rules:
  - host: lastmile.local
    http:
      paths:
      - path: /kibana(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: kibana
            port:
              number: 5601
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: lastmile-gateway
            port:
              number: 8080
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend
            port:
              number: 3000
